### ISSUE TITLE
Policy issue when exporting as stack of pngs

### ISSUE THREAD

**Issue by LinusCDE** [bruot/pyrmexplorer#3]
Hi,

I've tried your software. It's working really well.  
However when exporting any document/notebook as "Stack of pngs" I get the following policy issue:
```
Traceback (most recent call last):
  File "/tmp/pyrmexplorer/rmexplorer/rmexplorerwindow.py", line 467, in filesListItemDoubleClicked
    self.downloadFile(parts[0], (fid, parts[1]), ext)
  File "/tmp/pyrmexplorer/rmexplorer/rmexplorerwindow.py", line 246, in downloadFile
    tools.downloadFile(fid, basePath, destRelPath, mode, self.settings)
  File "/tmp/pyrmexplorer/rmexplorer/tools.py", line 106, in downloadFile
    resolution=settings.value('PNGResolution', type=int)) as img:
  File "/usr/lib/python3.7/site-packages/wand/image.py", line 4601, in __init__
    self.read(file=file, resolution=resolution)
  File "/usr/lib/python3.7/site-packages/wand/image.py", line 4896, in read
    self.raise_exception()
  File "/usr/lib/python3.7/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = python3.7 path = /usr/bin pid = 9786
KCrash: Arguments: /usr/bin/python3.7 
KCrash: Attempting to start /usr/lib/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
[1]  + 9786 suspended (signal)  python __main__.py
```

I guess that it's related to ImageMaqick but I can't know for sure. Would be nice to add this to the FAQ in the Wiki.

**Comment by bruot** [comment]
Hi @LinusCDE , thanks for your feedback! It looks like you have [this issue](https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion). From what I read, the default ImageMagick security policy is different depending on the version installed. Recent versions should not raise an exception.

Can you try to add the following line to the `<policymap>` block of your ImageMagick's "policy.xml" file and see if it works?

```
<policy domain="coder" rights="read | write" pattern="PDF" />
```

If that works, I will edit the Wiki.

While I never saw that problem before (ImageMagick 7.0.8), I managed to trigger the error by adding the "opposite" policy:

```
<policy domain="coder" rights="policy" pattern="PDF" />
```

**Comment by LinusCDE** [comment]
Hi,  
sorry for the late response.  
I've added the rule to to `/etc/ImageMagick-7/policy.xml` but it didn't yield any success.

The exception seems to be the same:
```
Traceback (most recent call last):                                                                                                                                                        
  File "/tmp/pyrmexplorer/rmexplorer/rmexplorerwindow.py", line 467, in filesListItemDoubleClicked                                                                                        
    self.downloadFile(parts[0], (fid, parts[1]), ext)                                                                                                                                     
  File "/tmp/pyrmexplorer/rmexplorer/rmexplorerwindow.py", line 246, in downloadFile                                                                                                      
    tools.downloadFile(fid, basePath, destRelPath, mode, self.settings)                                                                                                                   
  File "/tmp/pyrmexplorer/rmexplorer/tools.py", line 106, in downloadFile                                                                                                                 
    resolution=settings.value('PNGResolution', type=int)) as img:                                                                                                                         
  File "/usr/lib/python3.7/site-packages/wand/image.py", line 4601, in __init__                                                                                                           
    self.read(file=file, resolution=resolution)                                                                                                                                           
  File "/usr/lib/python3.7/site-packages/wand/image.py", line 4896, in read                                                                                                               
    self.raise_exception()                                                                                                                                                                
  File "/usr/lib/python3.7/site-packages/wand/resource.py", line 222, in raise_exception                                                                                                  
    raise e                                                                                                                                                                               
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408                                          
KCrash: crashing... crashRecursionCounter = 2                                                                                                                                             
KCrash: Application Name = python3.7 path = /usr/bin pid = 8541                                                                                                                           
KCrash: Arguments: /usr/bin/python3.7                                                                                                                                                     
KCrash: Attempting to start /usr/lib/drkonqi from kdeinit                                                                                                                                 
sock_file=/run/user/1000/kdeinit5__0                                                                                                                                                      
[1]  + 8541 suspended (signal)  python __main__.py
```

I have ImageMagick `7.0.8-45 Q16 x86_64 2019-05-131`.

**Comment by bruot** [comment]
I have now tested with Python 3 on Debian 8 and 9 installs in different configurations, using this simplified piece of code:

```
import io
import wand.image

with open('test.pdf', 'rb') as f:
    data = f.read()
with wand.image.Image(file=io.BytesIO(data),
                      resolution=360) as img:
    with img.convert('png') as converted:
        converted.save(filename='test.png')
```

Config 1:
- Debian 9 Stretch
- wand 0.5.3 installed from pip3
- ImageMagick 7.0.8-46 Q16 x86_64, compiled from sources

Config 2:
- Debian 9 Stretch
- wand 0.5.3 installed from pip3
- imagemagick 8:6.9.7.4+dfsg-11+deb9u7, imagemagick-6-common 8:6.9.7.4+dfsg-11+deb9u7, imagemagick-6-q16 8:6.9.7.4+dfsg-11+deb9u7 Debian packages installed.

Config 3:
- Debian 9 Stretch
- python3-wand 0.4.4-1.1 Debian package installed
- imagemagick 8:6.9.7.4+dfsg-11+deb9u7, imagemagick-6-common 8:6.9.7.4+dfsg-11+deb9u7, imagemagick-6-q16 8:6.9.7.4+dfsg-11+deb9u7 Debian packages installed.

Config 4:
- Debian 8 Jessie
- wand 0.5.3 installed from pip3
- imagemagick 8:6.8.9.9-5+deb8u16 Debian packages installed.

In all cases, the default security policy led to no errors.

@LinusCDE The error message you get is pretty clear - it should be able to resolve the issue by tuning the security policy. Be careful that some rules may override others (e.g. one with `pattern="*"`). If multiple policy.xml files exist on your system, be sure to modify the right one. Of course, the edited policy lines must also lie within the `<policymap>` and `</policymap>` tags.
